apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: aws-ebs
  spec:
    storageClassName: gp2
    claimRef:
      name: mongodb-pv-claim
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    persistentVolumeSource:
      awsEBS:
        volumeType: gp2
        volumeID: $VOLUMEID
        fsType: ext4
        region: $REGION 
        zone: $ZONE 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: gp2 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: $mongo_user
  MONGO_ROOT_PASSWORD: $mongo_password

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service 
  updateStrategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxDisruptionBudget: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4-bullseye 
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017